### ISSUE TITLE
Need advice on representations in this template

### ISSUE THREAD

**Issue by LettError** [roboDocs/single-windowcontroller-with-multiple-subscribers#1]
(a question, not an issue) Thank you for this very useful template. It seems to be the answer to a couple of my Merz / Subscriber issues :) 

I'm working on something that needs to draw shapes in Merz, based on calculations and data from pulled from multiple layers or glyphs. While some of those calculations can certainly be written in the form of a representation, I want to ask whether it is advisable (speed, better separation of model and interface) or absolutely necessary. Writing *all* calculations as a representation might be difficult. And I could easily add the code in some sort of general "update" method that gets called in the `glyphEditorDid*` methods. But I don't know whether this is against the intentions in this template.

Looking at the code, I think the "work" for my purpose needs to happen here: https://github.com/roboDocs/single-windowcontroller-with-multiple-subscribers/blob/b8f9bd64c1bd69cdebe9b022e6c0e839ec2e6ede/source/code/tool.py#L77

Any advice you can give on this?

**Comment by roberto-arista** [comment]
AFAIK the biggest advantage of representations is out-of-the-box caching. They are not mandatory.
But I agree that it is difficult to make them work with inputs from multiple layers/glyphs.

I am not sure what's the best practice in this case. @typemytype what do you think?

**Comment by LettError** [comment]
I will start by putting as much as I can in representations, and leave the stuff that builds on different glyphs to the `glyphEditorDid*` methods. Maybe it will be sufficient :)

**Comment by roberto-arista** [comment]
Great, I'll consider this solved. Feel free to reopen for more questions!
